defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
    myapp-development:
      authenticator: "Moped"
      options:
        database_url: "mongodb://localhost:27017/myapp-development"
        collection: "users"
        username_column: "email"
        password_column: "encrypted_password"
        salt_column: "password_salt"